branch-defaults:
  default:
    environment: cevegas
    group_suffix: null
global:
  application_name: CanvasEarthServer
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli2
  repository: null
  sc: null
